### ISSUE TITLE
Active calendar days visibility improvement

### ISSUE THREAD

**Issue by XXXJetfireXXX** [Nriver/awesome-trilium#30]
### Description
A micro-tweak that lets you better see active calendar days (the ones that have a corresponding note in a journal)

### Demo
![image](https://github.com/Nriver/awesome-trilium/assets/43646178/9c900bb4-fd8d-4cc4-b953-34b177e1c39d)

### Code
```css
.calendar-dropdown-widget .calendar-date-exists{
    color: deepskyblue !important;
}
```
